version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
        - :80
    environment:
      - DB_HOST = mssql
    depends_on: 
        - ms-sql-server
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=1506V23h
        - MSSQL_PID=Express
    ports:
        - "1433:1433"